### ISSUE TITLE
Please consider adding the Duck Duck Go Privacy Essentials

### ISSUE THREAD

**Issue by triptych** [notriddle/shouldiblockads.com#1]
You've referenced a great collection of ad blockers, I am posting this as an issue like you requested to consider adding Duck Duck Go Privacy Essentials to the list https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg

I'm not affiliated with them, just someone who's been using this blocker to great effect along with their search engine.

**Comment by notriddle** [comment]
I don't think so.

* I don't want to list every blocker there is. I'm going to put my foot down, and enshrine it in the README: **no more than five ad blockers**. The number is arbitrary, but I want to draw the line somewhere.

* The goal of this list is to list the best ad blockers I know of. This is subjective, I admit, but some of my criteria for choosing an ad blocker are: good out-of-the-box settings (which precludes the "acceptable ads program", because the standards list [doesn't even mention fraud, malware, or tracking](https://acceptableads.com/en/standard)), the ability to unbreak web pages that try to block your blocker, being popular enough that it's subject to media scrutiny in case the developer goes rogue and/or sells it, being easy to install, and not having any alternatives that are clearly better (pi-hole is exempt from multiple of the previous rules, specifically because there isn't anything clearly better: there aren't really any other ways to block ads on a locked-down smart TV other than pi-hole or something equally hard to set up).

* [It's slow](https://whotracks.me/blog/adblockers_performance_study.html). DuckDuckGo Privacy Essentials is the slowest blocker that I have numbers for. If I was going to recommend a "privacy blocker," I would recommend something else based on that alone.

**Comment by triptych** [comment]
Thanks for your consideration and comments.
