### ISSUE TITLE
Please consider adding Better to the Safari alternatives list

### ISSUE THREAD

**Issue by pedrolucasp** [notriddle/shouldiblockads.com#4]
Even though Better is a paid app, is built by long time surveillance capitalism 
activists and is layered on top of very careful choosen and transparent ethics.

https://better.fyi

**Comment by WaLLy3K** [comment]
> Even though Better is a paid app

1Blocker is free to install and enable one category (Ads, Trackers, Annoyances, Widgets, Comments, Adults Sites), but requires $5 monthly, $25 annually or $61 for lifetime. Yikes.

I sunk the couple of dollars for Better Blocker on the Mac App Store and putting it on Safari over my Pi-hole enabled network does collapse advertising elements as expected on something like `nytimes.com`.

Despite my limited testing, I'd definitely be more inclined to offer this as an affordable solution for Safari users.

**Comment by pedrolucasp** [comment]
Also, forgot to mention, but there's the option of messing with the hosts file as well.

https://github.com/StevenBlack/hosts

**Comment by notriddle** [comment]
The price difference seems like a good enough reason. I've added Better.

I won't be adding a hosts file, [because you can't unbreak pages with a hosts file](https://github.com/gorhill/uBlock/wiki/Counterarguments#just-use-a-hosts-file). I know that the same argument applies to pi-hole, but pi-hole covers an entire network at once, so it's worth it (the fact that you can't unbreak pages with pi-hole is also why I listed it last).

**Comment by WaLLy3K** [comment]
> I won't be adding a hosts file, because you can't unbreak pages with a hosts file. I know that the same argument applies to pi-hole, but pi-hole covers an entire network at once, so it's worth it (the fact that you can't unbreak pages with pi-hole is also why I listed it last).

You can whitelist sites globally, or on a per client basis. Hosts files are harder to maintain, and generally need to be updated manually. I definitely agree with listing Pi-hole over a hosts file recommendation. :)
